### ISSUE TITLE
help

### ISSUE THREAD

**Issue by app-johndpope** [AluBhorta/UCSPy-Engine#3]
Traceback (most recent call last):
  File "/Users/johnpope/Documents/gitWorkspace/UCSPy-Engine/cli.py", line 6, in <module>
    fire.Fire(UCSPyEngine)
  File "/Users/johnpope/miniconda3/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/Users/johnpope/miniconda3/lib/python3.9/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/Users/johnpope/miniconda3/lib/python3.9/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/Users/johnpope/Documents/gitWorkspace/UCSPy-Engine/core/models/UCSPyEngine.py", line 34, in inspect
    return ScheduleInspector(
TypeError: inspect() missing 1 required positional argument: 'schedule_file'

I run the 
python cli.py solve
but no schedule is spat out
I run inspect - but it's asking for scedule file

**Comment by app-johndpope** [comment]
fixed - 

  "save_logs": true,
  "save_schedule": true,
  "inspect_final_schedule": true,


Course,Section,Instructor,Room,Timeslot
CSC101,1,Mr. Fahad Monir,5014,ST 08:00-09:30
CSC101,2,Mr. Fahad Monir,GPL,ST 09:40-11:10
CSC101,3,Dr. Ashraful Amin,CSCLAB2,ST 08:00-09:30
CSC101,4,Mr. Fahad Monir,5013,ST 11:20-12:50
CSC101,5,Mr. Mohammad Motiur Rahman,6007,ST 08:00-09:30
CSC101L,1,Mr. Fahad Monir,5013,S 13:40-15:10
CSC101L,2,Mr. Mohammad Motiur Rahman,10017,T 08:00-09:30
CSC101L,3,Dr. Ashraful Amin,3009,S 09:40-11:10
CSC101L,4,Mr. Fahad Monir,10015,S 15:20-16:50
CSC101L,5,Mr. Fahad Monir,5014,S 17:00-18:30
CSC121,1,Mr. Subrata Dey,6013,ST 08:00-09:30
CSC121L,1,Mr. Subrata Dey,7015,W 08:00-09:30
CSE104,1,Ms. Ajmiri Sabrina Khan,CSCLAB4,ST 08:00-09:30
CSE104,2,Dr. Ferdows Zahid,5013,ST 08:00-09:30
CSE104,3,Ms. Ajmiri Sabrina Khan,8013,ST 09:40-11:10
CSE104,4,Dr. Ferdows Zahid,6008,ST 09:40-11:10
CSE104L,1,Dr. Ferdows Zahid,10015,S 11:20-12:50
CSE104L,2,Dr. Ferdows Zahid,7015,S 13:40-15:10
CSE104L,3,Dr. Ferdows Zahid,6013,T 09:40-11:10
CSE104L,4,Dr. Ferdows Zahid,CSCLAB2,M 13:40-15:10
CSE201,1,Md. Shariful Islam,5002,MW 17:00-18:30
CSE201,2,Md. Shariful Islam,6013,ST 09:40-11:10
CSE201,3,Dr. Habib Bin Muzaffar,6009,ST 08:00-09:30
CSE203,1,Mr. Mohammad Motiur Rahman,6007,MW 17:00-18:30
CSE203,2,Ms. Romasa Qasim,GPL,ST 08:00-09:30
CSE203,3,Mr. Mohammad Motiur Rahman,10017,ST 13:40-15:10
CSE203,4,Mr. Mohammad Motiur Rahman,6013,ST 15:20-16:50
CSE203,5,Mr. Mohammad Motiur Rahman,7026,ST 17:00-18:30
CSE203L,1,Mr. Mohammad Motiur Rahman,CENLab,T 09:40-11:10
CSE203L,2,Dr. AKM Mahbubur Rahman,CSCLAB1,S 08:00-09:30
CSE203L,3,Mr. Mohammad Motiur Rahman,CSCLAB1,M 08:00-09:30
CSE203L,4,Mr. Asif Bin Khaled,CSCLAB4,S 08:00-09:30
CSE203L,5,Mr. Asif Bin Khaled,7026,S 09:40-11:10
CSE204,1,Mr. Raihan Bin Rafique,6012,ST 08:00-09:30
CSE204,2,Mr. Raihan Bin Rafique,6009,ST 09:40-11:10
CSE204,3,Mr. Md. Abu Sayeed,10014,ST 08:00-09:30
CSE204,4,Mr. Raihan Bin Rafique,CSCLAB4,ST 11:20-12:50
CSE204L,1,Mr. Md. Abu Sayeed,CENLab,M 11:20-12:50
CSE204L,2,Mr. Raihan Bin Rafique,6013,S 08:00-09:30
CSE204L,3,Mr. Raihan Bin Rafique,CENLab,S 15:20-16:50
CSE204L,4,Mr. Raihan Bin Rafique,6012,S 17:00-18:30
CSE210,1,Ms. Ajmiri Sabrina Khan,9014,ST 11:20-12:50
CSE210,2,Dr. Faisal M. Uddin,7015,ST 08:00-09:30
CSE210,3,Ms. Ajmiri Sabrina Khan,6008,ST 13:40-15:10
CSE210L,1,Dr. Faisal M. Uddin,CSCLAB1,S 09:40-11:10
CSE210L,2,Dr. Faisal M. Uddin,6009,S 11:20-12:50
CSE210L,3,Ms. Ajmiri Sabrina Khan,5012,S 15:20-16:50
CSE211,1,Dr. Ali Shihab Sabbir,10017,ST 08:00-09:30
CSE211,2,Mr. Asif Bin Khaled,GPL,ST 11:20-12:50
CSE211,3,Mr. Bijoy Rahman Arif,9014,ST 08:00-09:30
CSE211L,1,Mr. Bijoy Rahman Arif,CSCLAB4,MW 17:00-18:30
CSE211L,2,Mr. Bijoy Rahman Arif,5014,S 11:20-12:50
CSE211L,3,Mr. Asif Bin Khaled,CSCLAB3,S 13:40-15:10
CSE213,1,Mr. Subrata Dey,6008,ST 11:20-12:50
CSE213,2,Mr. Subrata Dey,8013,ST 13:40-15:10
CSE213,3,Mr. Subrata Dey,CSCLAB3,MW 17:00-18:30
CSE213L,1,Mr. Subrata Dey,10014,T 08:00-09:30
CSE213L,2,Mr. Subrata Dey,CSCLAB2,T 09:40-11:10
CSE213L,3,Mr. Subrata Dey,CSCLAB1,T 17:00-18:30
CSE214,1,Mr. Noor Nabi,7026,ST 08:00-09:30
CSE214,2,Mr. Noor Nabi,5002,ST 09:40-11:10
CSE216,1,Mr. Raihan Bin Rafique,9014,MW 08:00-09:30
CSE216,2,Mr. Raihan Bin Rafique,7026,MW 09:40-11:10
CSE216L,1,Mr. Raihan Bin Rafique,10015,T 08:00-09:30
CSE216L,2,Mr. Raihan Bin Rafique,9014,T 15:20-16:50
CSE303,1,Dr. Mahady Hasan,6008,ST 08:00-09:30
CSE303,2,Ms. Radiah Haque,4043,ST 08:00-09:30
CSE303L,1,Dr. Mahady Hasan,CSCLAB3,S 09:40-11:10
CSE303L,2,Ms. Radiah Haque,9014,S 09:40-11:10
CSE307,1,Ms. Radiah Haque,10017,ST 11:20-12:50
CSE307,2,Ms. Radiah Haque,6007,ST 13:40-15:10
CSE309,1,Ms. Shama Hoque,CSCLAB1,ST 08:00-09:30
CSE309,2,Ms. Shama Hoque,6007,ST 09:40-11:10
CSE310,1,Dr. Ferdows Zahid,5014,ST 11:20-12:50
CSE310,2,Dr. Ferdows Zahid,7015,MW 09:40-11:10
CSE310L,1,Dr. Ferdows Zahid,CENLab,T 11:20-12:50
CSE310L,2,Dr. Ferdows Zahid,6008,T 13:40-15:10
CSE313,1,Mr. Bijoy Rahman Arif,GPL,ST 13:40-15:10
CSE313,2,Mr. Bijoy Rahman Arif,5002,ST 15:20-16:50
CSE315,1,Mr. Noor Nabi,5002,ST 11:20-12:50
CSE315,2,Mr. Noor Nabi,6012,ST 13:40-15:10
CSE316,1,Dr. Tarem Ahmed,CSCLAB3,ST 08:00-09:30
CSE316,2,Mr. Fahad Monir,6013,MW 08:00-09:30
CSE316L,1,Dr. Tarem Ahmed,GPL,S 09:40-11:10
CSE316L,2,Mr. Fahad Monir,3009,T 13:40-15:10
CSE317,1,Dr. AKM Mahbubur Rahman,5013,ST 09:40-11:10
CSE317,2,Md. Shariful Islam,7015,ST 11:20-12:50
CSE317L,1,Dr. AKM Mahbubur Rahman,10014,S 11:20-12:50
CSE317L,2,Md. Shariful Islam,CSCLAB2,S 13:40-15:10
CSE402,1,Dr. Faisal M. Uddin,GPL,W 09:40-11:10
CSE 437,1,Mr. Bijoy Rahman Arif,6009,S 17:00-18:30
CSE 437,2,Dr. Ali Shihab Sabbir,6012,S 18:30-21:30
CSE 417,1,Mohammad Shibli Kaysar,6008,S 18:30-21:30
CSE 417,2,Mohammad Shibli Kaysar,7015,T 18:30-21:30
CSE421,1,Dr. Amin Ahsan Ali,7026,S 18:30-21:30
CSE425,1,Dr. Amin Ahsan Ali,7026,T 18:30-21:30
CSE426,1,Dr. Mohammed Anwer,5014,S 18:30-21:30
CSE451,1,Dr. Mahady Hasan,6007,S 17:00-18:30
CSE 458,1,Ms. Nujhat Nahar,6013,M 08:00-09:30
CSE 458,2,Ms. Nujhat Nahar,7015,S 15:20-16:50
CSE453,1,Ms. Radiah Haque,10014,S 18:30-21:30
CSE464,1,Sanzar Adnan Alam,CSCLAB4,T 17:00-18:30
CSE471,1,Dr. AKM Mahbubur Rahman,9014,S 18:30-21:30





Course,Section,Instructor,Room,Timeslot
0,1,15,11,0
0,2,15,5,1
0,3,3,1,0
0,4,15,10,2
0,5,2,12,0
1,1,15,10,15
1,2,2,23,19
1,3,3,6,13
1,4,15,22,16
1,5,15,11,17
2,1,13,16,0
3,1,13,17,33
4,1,16,3,0
4,2,1,10,0
4,3,16,19,1
4,4,1,13,1
5,1,1,22,14
5,2,1,17,15
5,3,1,16,20
5,4,1,1,29
6,1,22,8,11
6,2,22,16,1
6,3,26,14,0
7,1,2,12,11
7,2,18,5,0
7,3,2,23,3
7,4,2,16,4
7,5,2,18,5
8,1,2,4,20
8,2,7,0,12
8,3,2,0,26
8,4,17,3,12
8,5,17,18,13
9,1,0,15,0
9,2,0,14,1
9,3,10,21,0
9,4,0,3,2
10,1,10,4,28
10,2,0,16,12
10,3,0,4,16
10,4,0,15,17
11,1,16,20,2
11,2,4,17,0
11,3,16,13,3
12,1,4,0,13
12,2,4,14,14
12,3,16,9,16
13,1,8,23,0
13,2,17,5,2
13,3,14,20,0
14,1,14,3,11
14,2,14,11,14
14,3,17,2,15
15,1,13,13,2
15,2,13,19,3
15,3,13,2,11
16,1,13,21,19
16,2,13,1,20
16,3,13,0,24
17,1,6,18,0
17,2,6,8,1
18,1,0,20,6
18,2,0,18,7
19,1,0,22,19
19,2,0,20,23
20,1,9,13,0
20,2,11,7,0
21,1,9,2,13
21,2,11,20,13
22,1,11,23,2
22,2,11,12,3
23,1,21,0,0
23,2,21,12,1
24,1,1,11,2
24,2,1,17,7
25,1,1,4,21
25,2,1,13,22
26,1,14,5,3
26,2,14,8,4
27,1,6,8,2
27,2,6,15,3
28,1,5,2,0
28,2,15,16,6
29,1,5,5,13
29,2,15,6,22
30,1,7,10,1
30,2,22,17,2
31,1,7,21,14
31,2,22,1,15
32,1,4,5,34
33,1,14,14,17
33,2,8,15,18
34,1,23,13,18
34,2,23,17,25
35,1,12,18,18
36,1,12,18,25
37,1,28,11,18
38,1,9,12,17
39,1,24,16,26
39,2,24,17,16
40,1,11,21,18
41,1,19,3,24
42,1,7,20,18
